//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfProject2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logowanie
    {
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<bool> UserType { get; set; }
        public bool Blocked { get; set; }
        public string Surname { get; set; }
        public byte WrongAttempts { get; set; }
    }
}
